In [3]:
%load_ext autoreload
%autoreload 2
from utils import *
from feature_extraction import images_Dictionary

In [2]:
a =np.array(['cq', 'dq'])
b =np.array(['c', 'd'])
x=np.append(a, b, axis=None)
print(x)


['cq' 'dq' 'c' 'd']


In [5]:
images_men={}
#Men Images
images_men=images_Dictionary("../outputs/preprocessing_output/men/")
# print(images)
print(np.shape(images_men['0']))

# # Add Women Images
images_women={}
images_men=images_Dictionary("../outputs/preprocessing_output/women/")
# print(images)
print(np.shape(images_women['0']))

images={}
for i in range(0,6):
    print(i)
    images[str(i)]=np.concatenate((images_men[str(i)],images_women[str(i)]),axis=0)

print(np.shape(images['0']))


KeyError: '0'

In [20]:
import numpy as np
  
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])
  
gfg = np.concatenate((arr1, arr2), axis = 0)
print(gfg)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [9]:
import numpy as np
a={}
print(a.get('a'))
if(a.get('a') is None):
    a.update({"a": [1,2,3]})
else:
    a['a'].append([5,6])

print(a)

a['a'].append([5,6])
print(a)

None
{'a': [1, 2, 3]}
{'a': [1, 2, 3, [5, 6]]}


In [18]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x=np.insert(x,values=np.array([1,2,3,4]))
# x=np.append(x,np.array([1,2,3,4]))
print(x)


TypeError: _insert_dispatcher() missing 1 required positional argument: 'obj'

In [34]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
np.vstack([arr,np.array([5,6,8])])

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 8]])

In [2]:
x=[1,2]
x.append(3)
print(x)

[1, 2, 3]


In [6]:
import numpy as np
a={'a':np.array([1,3,5]),
'b':np.array([1,3,5])
}
print(a.values())

dict_values([array([1, 3, 5]), array([1, 3, 5])])


In [22]:
import pandas as pd
d = {'a': np.array([[1, 2, 3],[4, 5, 6]]),
      'b': np.array([[7,8,9],[10,11,12]]),
      'c': np.array([[13,14,15],[16,17,18]])}

# df = pd.DataFrame({k:list(v) for k,v in d.items()})
# print(df)
all_feature_descriptors=[]
for fd in d.values():
    print(fd)
    all_feature_descriptors.append(fd)

# print(np.array(all_feature_descriptors).flatten())
print(np.array(all_feature_descriptors).reshape(-1,3))
# print(np.shape(all_feature_descriptors))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
